### ISSUE TITLE
驳回操作

### ISSUE THREAD

**Issue by ahjsyangliang** [Shurlormes/Activiti#1]
你有研究6.0版本的驳回操作吗?

**Comment by Shurlormes** [comment]
你可以使用gateway。
两个例子随便一个都可以
一：直接传结果
https://github.com/Shurlormes/Activiti/blob/master/src/main/resources/processes/exclusiveTest.bpmn
https://github.com/Shurlormes/Activiti/blob/95d0975b194c18b1a1afe8f5d145a2ddc7ff8423/src/test/java/FlowTest.java#L58

二：根据传递参数判断是否符合条件
https://github.com/Shurlormes/Activiti/blob/master/src/main/resources/processes/gateweyTest.bpmn
https://github.com/Shurlormes/Activiti/blob/95d0975b194c18b1a1afe8f5d145a2ddc7ff8423/src/test/java/FlowTest.java#L33

**Comment by Shurlormes** [comment]
可以考虑用子任务
https://github.com/Shurlormes/Activiti/blob/master/src/main/resources/processes/cancelSubTest.bpmn

https://github.com/Shurlormes/Activiti/blob/95d0975b194c18b1a1afe8f5d145a2ddc7ff8423/src/test/java/SubProcessTest.java#L99

也可以用gateway，写好判断条件。

只需要把流程画好
